### ISSUE TITLE
injectGlobal does not accept composes

### ISSUE THREAD

**Issue by thejameskyle** [tkh44/emotion#156]
- `emotion` version: 6.0.1
- `react` version: 15.6.1

**Input**

```js
import {css, injectGlobal} from 'emotion';

let foo = css`
  color: red;
`;

injectGlobal`
  .bar {
    composes: ${foo}
  }
`;
```

**Output**

```css
.bar {
    composes: css-foo-6td1rg-1wy6q4a css-foo-6td1rg;
}
```

Not sure if there is a technical reason for this, but it would be nice to have.
