### ISSUE TITLE
Autoprefixer ignores configuration

### ISSUE THREAD

**Issue by onnovisser** [tkh44/emotion#242]
- `emotion` version: 7.0.11
- `react` version: 16.0.0-alpha.13

Relevant code.

```javascript
const Styled = styled.div`
  display: flex;
`
```

Problem description:
I tried to configure Autoprefixer by setting the Browserslist config in a few ways

 - Using the browserslist key in the package json:
```json
"browserslist": [
  "last 1 Chrome version"
],
``` 

 - Having a .browserslistrc
```
[production]
last 1 Chrome version

[development]
last 1 Chrome version
```

- Setting the BROWSERSLIST environment variable. `BROWSERSLIST="last 1 Chrome version"`

What happened:

Only when setting the env variable did I get the expected result:
```css
.css-1fe3owl {
    display: flex;
}
```

In the other two cases I got:
```css
.css-71uu79 {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
}
```
