### ISSUE TITLE
Expression interpolation in injectGlobal

### ISSUE THREAD

**Issue by bfin** [tkh44/emotion#284]
- `emotion` version: 7.2.0
- `react` version: 15.6.1

```javascript
import { injectGlobal } from 'emotion'

const headerElements = {
  h1: 4,
  h2: 3,
  h3: 2,
  h4: 1,
}

const makeStyleString = (element, rems) => `${element} { font-size: ${rems}rem; }`
const styles = Object.keys(headerElements).map(x => makeStyleString(x, headerElements[x]))
const stylesBlock = styles.join('\n')

injectGlobal`
  ${stylesBlock}
`
```

I'm attempting to set up some global styles using `injectGlobal`: above is a very basic example.

I was expected the following block of styles:
```text
h1 { font-size: 4rem; }
h2 { font-size: 3rem; }
h3 { font-size: 2rem; }
h4 { font-size: 1rem; }
```

But no styles were output.

This is trivial using preprocessors like Stylus:
```stylus
headerElements = {
  h1: 4,
  h2: 3,
  h3: 2,
  h4: 1,
}

for element, rems in headerElements
  element
    font-size: rems rem
```

Of course, manual interpolation works just fine:
```javascript
injectGlobal`
  h1 { font-size: ${headerElements.h1}; }
  h2 ...
`
```
...but this quickly gets tedious.

What am I missing here?!!!

**Comment by bfin** [comment]
For what it's worth, I'm currently using something like this:

```javascript
import { css, injectGlobal } from 'emotion'

const headerElements = {
  h1: 4,
  h2: 3,
  h3: 2,
  h4: 1,
}

const styles = Object.keys(headerElements).reduce((accumulator, key) => {
  accumulator[key] = css`font-size: ${headerElements[key]}rem`
  return accumulator
}, {})

injectGlobal`
  h1 {
    ${styles.h1};
  }
  h2 {
    ${styles.h2};
  }
  h3 {
    ${styles.h3};
  }
  h4 {
    ${styles.h4};
  }
`
```

As expected, it generates classes for each style and also applies them to the elements:
```css
.css-xxtg95{font-size:4rem;}
.css-hj4e5e{font-size:3rem;}
.css-1oic13s{font-size:2rem;}
.css-1h3rrcl{font-size:1rem;}
h1{font-size:4rem;}
h2{font-size:3rem;}
h3{font-size:2rem;}
h4{font-size:1rem;}
```

I'd just like to be able to do this in cases where I don't need a class generated for each style.

**Comment by tkh44** [comment]
Just out of curiousity does this work?
```
const styles = Object.keys(headerElements).reduce((accumulator, key) => {
  accumulator[key] = css`${key} { font-size: ${headerElements[key]}rem }`
  return accumulator
}, {})
```

**Comment by bfin** [comment]
@tkh44 , thanks for the input.

Including the element in the argument to `css` produces the same output as my current solution. That is, it first generates css classes and then applies the styles to the elements:
```css
.css-xxtg95{font-size:4rem;}
.css-hj4e5e{font-size:3rem;}
.css-1oic13s{font-size:2rem;}
.css-1h3rrcl{font-size:1rem;}
h1{font-size:4rem;}
h2{font-size:3rem;}
h3{font-size:2rem;}
h4{font-size:1rem;}
```

For styles that I'm certain I won't be applying elsewhere, your solution does save some keystrokes. What is mystifying to me – though probably quite obvious to you – is why passing even a simple string won't work, e.g.:
```javascript
const styles = 'h1{font-size:4rem;}h2{font-size:3rem;}h3{font-size:2rem;}h4{font-size:1rem;}'

injectGlobal`
  ${styles}
`
```
...produces the styles but does NOT apply them to elements:
```css
.css-yazff5h1{font-size:4rem;}
.css-d24qd6h2{font-size:3rem;}
.css-1k98u62h3{font-size:2rem;}
.css-ualo1th4{font-size:1rem;}
```

I'm trying for the opposite!

Honestly, generating the styles independently and then explicitly applying them to elements in `injectGlobal` isn't much extra work and the 'extra' classes don't add that much bloat. I just thought I might be missing something obvious (aside from my clear misunderstanding of how `emotion` works...grin).
